spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false # OSIV 비활성화
discodeit:
  storage:
    type: local